# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
    push:
        branches: [main]

jobs:
    build:

        runs-on: ubuntu-latest

        steps:
           -  name: Checkout code
              uses: actions/checkout@v4

           -  name: Setup .NET
              uses: actions/setup-dotnet@v4
              with:
                  dotnet-version: 10.0.0

           -  name: Install .NET Framework 4.5.2 Developer Pack
              run: |
                  sudo dpkg --add-architecture i386
                  sudo apt-get update
                  sudo apt-get install -y \
                    wine64 \
                    libwine:i386 \
                    libwine-development:i386 \
                    wine \
                    wine-stable \
                    wine64-development

           -  name: Restore dependencies
              run: dotnet restore ApnaBank
              working-directory: ApnaBank

           -  name: Update MSBuild
              run: dotnet tool update -g msbuild --version 16.9.0

           -  name: Build
              run: dotnet build --configuration Release ApnaBank
              working-directory: ApnaBank
