# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET
on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 5.0.403
      - name: Restore dependencies
        run: nuget restore ApnaBank/ApnaBank.sln
      - name: Build
        run: >
          "C:\Program Files\dotnet\dotnet.exe" build --configuration Release
          ApnaBank/ApnaBank/ApnaBank.csproj
