# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 4.5.2  # Choose a version that is compatible with your project

    - name: Restore dependencies
      run: dotnet restore
      working-directory: ApnaBank

    - name: Build
      run: dotnet build --configuration Release
      working-directory: ApnaBank



